---
#tag::random-port[]
micronaut:
    server:
        port: -1
#end::random-port[]
    application:
        name: clubs

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#tag::jpa[]
jpa:
  default:
    packages-to-scan:
    - 'clubs.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]


---
datasources.default: {}

#tag::consul[]
---
consul:
  client:
    registration:
      enabled: true
  defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
#end::consul[]
